[package]
name = "blackdragonchest"
version = "0.1.0"
edition = "2021"

[dependencies]
near-crypto = "0.22.0"
near-sdk = { version = "5.1.0", features = [ "legacy"] }
wee_alloc = "0.4.5"
borsh = "1.5.1"
rand= "0.7.3"
getrandom = { version = "0.2", features = ["js"] }

